# Generated by Django 5.0.4 on 2024-04-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_card_last_review_card_review_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='review_count',
            field=models.IntegerField(default=1),
        ),
    ]
