# Generated by Django 5.0.4 on 2024-04-14 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_card_review_count'),
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deck.deck'),
            preserve_default=False,
        ),
    ]
