# Generated by Django 5.0.4 on 2024-04-08 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
